site_name: LangChain Land Use Analysis
site_description: Analyze county-level land use transitions using LangChain agents and natural language queries
site_author: Your Name
site_url: https://your-domain.com/langchain-landuse

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
  language: en
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/yourusername/langchain-landuse
repo_name: langchain-landuse

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Natural Language Queries:
    - Overview: queries/overview.md
    - Basic Queries: queries/basic-queries.md
    - Advanced Queries: queries/advanced-queries.md
    - Query Examples: queries/examples.md
  - Data & Schemas:
    - Data Sources: data/sources.md
    - Database Schema: data/schema.md
    - Land Use Categories: data/categories.md
    - Data Processing: data/processing.md
  - API Reference:
    - Data Engineering Agent: api/agent.md
    - Converters: api/converters.md
    - Tools & Utilities: api/tools.md
  - Examples:
    - Use Cases: examples/use-cases.md
    - Sample Workflows: examples/workflows.md
    - Jupyter Notebooks: examples/notebooks.md
  - Development:
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Testing: development/testing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: yourusername
      repo: langchain-landuse
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
  analytics:
    provider: google
    property: G-XXXXXXXXXX

copyright: |
  &copy; 2025 <a href="https://github.com/yourusername"  target="_blank" rel="noopener">Your Name</a>