[global]
# Show debug information
developmentMode = false

[server]
# Port configuration
port = 8501
headless = false

# Enable CORS for local development
enableCORS = false
enableXsrfProtection = false

# File upload settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Automatically open browser when starting
gatherUsageStats = false

[theme]
# Modern theme configuration
primaryColor = "#2E86AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Show sidebar navigation
showSidebarNavigation = true

# Toolbar mode
toolbarMode = "auto"

[ui]
# Hide deploy button and menu
hideTopBar = false
hideSidebarNav = false